# CMake generated Testfile for 
# Source directory: /home/rmcd/git/bmi-prms6-streamflow/tests
# Build directory: /home/rmcd/git/bmi-prms6-streamflow/_build/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(test_get_component_name "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_get_component_name")
set_tests_properties(test_get_component_name PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;12;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_get_input_item_count "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_get_input_item_count")
set_tests_properties(test_get_input_item_count PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;13;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_get_output_item_count "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_get_output_item_count")
set_tests_properties(test_get_output_item_count PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;14;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_get_input_var_names "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_get_input_var_names")
set_tests_properties(test_get_input_var_names PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;15;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_get_output_var_names "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_get_output_var_names")
set_tests_properties(test_get_output_var_names PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;16;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_initialize "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_initialize")
set_tests_properties(test_initialize PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;17;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_finalize "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_finalize")
set_tests_properties(test_finalize PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;18;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_update "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_update")
set_tests_properties(test_update PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;19;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_update_until "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_update_until")
set_tests_properties(test_update_until PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;20;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_get_start_time "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_get_start_time")
set_tests_properties(test_get_start_time PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;21;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_get_end_time "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_get_end_time")
set_tests_properties(test_get_end_time PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;22;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_get_current_time "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_get_current_time")
set_tests_properties(test_get_current_time PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;23;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_get_time_step "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_get_time_step")
set_tests_properties(test_get_time_step PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;24;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_get_time_units "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_get_time_units")
set_tests_properties(test_get_time_units PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;25;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_get_var_grid "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_get_var_grid")
set_tests_properties(test_get_var_grid PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;26;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_get_var_type "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_get_var_type")
set_tests_properties(test_get_var_type PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;27;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_get_var_units "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_get_var_units")
set_tests_properties(test_get_var_units PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;28;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_get_var_itemsize "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_get_var_itemsize")
set_tests_properties(test_get_var_itemsize PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;29;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_get_var_nbytes "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_get_var_nbytes")
set_tests_properties(test_get_var_nbytes PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;30;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_get_var_location "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_get_var_location")
set_tests_properties(test_get_var_location PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;31;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_get_grid_type "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_get_grid_type")
set_tests_properties(test_get_grid_type PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;32;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_get_grid_rank "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_get_grid_rank")
set_tests_properties(test_get_grid_rank PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;33;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_get_grid_size "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_get_grid_size")
set_tests_properties(test_get_grid_size PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;34;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_get_grid_shape "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_get_grid_shape")
set_tests_properties(test_get_grid_shape PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;35;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_get_grid_spacing "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_get_grid_spacing")
set_tests_properties(test_get_grid_spacing PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;36;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_get_grid_origin "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_get_grid_origin")
set_tests_properties(test_get_grid_origin PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;37;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_get_grid_x "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_get_grid_x")
set_tests_properties(test_get_grid_x PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;38;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_get_grid_y "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_get_grid_y")
set_tests_properties(test_get_grid_y PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;39;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_get_grid_z "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_get_grid_z")
set_tests_properties(test_get_grid_z PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;40;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_get_grid_node_count "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_get_grid_node_count")
set_tests_properties(test_get_grid_node_count PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;41;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_get_grid_edge_count "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_get_grid_edge_count")
set_tests_properties(test_get_grid_edge_count PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;42;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_get_grid_face_count "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_get_grid_face_count")
set_tests_properties(test_get_grid_face_count PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;43;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_get_grid_edge_nodes "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_get_grid_edge_nodes")
set_tests_properties(test_get_grid_edge_nodes PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;44;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_get_grid_face_edges "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_get_grid_face_edges")
set_tests_properties(test_get_grid_face_edges PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;45;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_get_grid_face_nodes "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_get_grid_face_nodes")
set_tests_properties(test_get_grid_face_nodes PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;46;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_get_grid_nodes_per_face "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_get_grid_nodes_per_face")
set_tests_properties(test_get_grid_nodes_per_face PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;47;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_get_value "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_get_value")
set_tests_properties(test_get_value PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;48;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_get_value_ptr "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_get_value_ptr")
set_tests_properties(test_get_value_ptr PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;49;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_get_value_at_indices "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_get_value_at_indices")
set_tests_properties(test_get_value_at_indices PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;50;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_set_value "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_set_value")
set_tests_properties(test_set_value PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;51;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
add_test(test_set_value_at_indices "/home/rmcd/git/bmi-prms6-streamflow/_build/tests/test_set_value_at_indices")
set_tests_properties(test_set_value_at_indices PROPERTIES  _BACKTRACE_TRIPLES "/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;7;add_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;52;make_test;/home/rmcd/git/bmi-prms6-streamflow/tests/CMakeLists.txt;0;")
